---
development:
  cloud_name: drv58qoek
  api_key: '111998552118955'
  api_secret: EwlfXyvtXzrg3ft_Nn0B-ry5oZ4
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: drv58qoek
  api_key: '111998552118955'
  api_secret: EwlfXyvtXzrg3ft_Nn0B-ry5oZ4
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: drv58qoek
  api_key: '111998552118955'
  api_secret: EwlfXyvtXzrg3ft_Nn0B-ry5oZ4
  enhance_image_tag: true
  static_file_support: false
